apiVersion: v1
kind: ConfigMap
metadata:
  name: github-postmortem-prometheus
data:
  GITHUB_USERNAME: quipper
  GITHUB_REPONAME: quipper
  GITHUB_TOKEN: secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: github-postmortem-prometheus
  name: github-postmortem-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-postmortem-prometheus
  template:
    metadata:
      annotations:
        ad.datadoghq.com/github-postmortem-prometheus.check_names: |
          ["openmetrics"]
        ad.datadoghq.com/github-postmortem-prometheus.init_configs: |
          [{}]
        ad.datadoghq.com/github-postmortem-prometheus.instances: |
          [
            {
              "prometheus_url": "http://%%host%%:8000/metrics",
              "metrics": ["github_postmortem_*"],
              "label_to_hostname": "full_reponame"
            }
          ]
      labels:
        app: github-postmortem-prometheus
    spec:
      containers:
        - name: github-postmortem-prometheus
          image: chaspy/github-postmortem-prometheus
          envFrom:
            - configMapRef:
                name: github-postmortem-prometheus
